baseURL = "https://aralybarrera.com/"
languageCode = "en-us"
title = "Araly Barrerra : photographer"
theme = "ananke"

[params]
description="World-wide photographer."
site_logo="/images/logo.png"
featured_image="/images/flowers.jpg"
#background_color_class="bg-white"
#body_classes="avenir bg-black"
#omit_header_text=true
instagram="https://instagram.com"
