baseURL = "https://aralybarrera.com/"
languageCode = "en-us"
title = "Araly Barrerra : photographer"
theme = "hugo-creative-portfolio-theme"


[params]
style="default"
description="World-wide photographer."
copyright = "&copy;2020 Araly Barrerra Photography"
sidebarAbout = ["A site/blog displaying my hobby as a photographer and photo editor!"]
[[params.navlinks]]
name = "Home"
url = "portfolio/"
home = true

[[params.navlinks]]
name = "About"
url = "about/"

[[params.navlinks]]
name = "Get in touch"
url = "contact/"

[params.social]
instagram = "https://instagram.com"


#site_logo="/images/logo.png"
featured_image="/images/flowers.jpg"
#background_color_class="bg-white"
#body_classes="avenir bg-black"
#omit_header_text=true
#instagram="https://instagram.com"
